version: '3.8'
services:
  melo-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - ${DB_PORT}:1433
    networks:
      - melo-net
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -C -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      retries: 5
      start_period: 60s

  rabbitmq:
    image: rabbitmq:4.0-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    networks:
      - melo-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
    depends_on:
      melo-db:
        condition: service_healthy
  
  melo-files:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-Files
    ports:
      - ${FILE_API_PORT}:7236
    volumes:
      - ./Melo.Files/Files:/app/Files
    environment:
      - ASPNETCORE_ENVIRONMENT=${FILE_API_ENV}
      - PUBLIC_HOST=localhost
      - PUBLIC_PORT=${FILE_API_PORT}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      - JWT_KEY=${JWT_KEY}
      - RABBITMQ_HOST_STRING=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      - VIEW_INTERVAL_MINUTES=${VIEW_INTERVAL_MINUTES}
      - VIEW_CACHE_EXPIRATION_MINUTES=${VIEW_CACHE_EXPIRATION_MINUTES}
    networks:
      - melo-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  melo-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-API
    ports:
      - ${MAIN_API_PORT}:7286
    volumes:
      - ./Melo.API/Recommendations:/app/Recommendations
    environment:
      - ASPNETCORE_ENVIRONMENT=${MAIN_API_ENV}
      - DB_CONNECTION_STRING=Server=melo-db,1433;Database=210038;User ID=sa;Password=${DB_PASSWORD};MultipleActiveResultSets=True;TrustServerCertificate=True
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      - JWT_KEY=${JWT_KEY}
      - REFRESH_TOKEN_EXPIRATION_MINUTES=${REFRESH_TOKEN_EXPIRATION_MINUTES}
      - FILE_SERVER_BASE_URL=http://melo-files:7236/api/
      - RABBITMQ_HOST_STRING=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      - RABBITMQ_SUBSCRIPTION_ID=melo_api
      - RECOMMENDER_MODEL_TRAINING_FREQUENCY_HOURS=${RECOMMENDER_MODEL_TRAINING_FREQUENCY_HOURS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
    networks:
      - melo-net
    depends_on:
      melo-files:
        condition: service_started

networks:
  melo-net:
    driver: bridge
